; NUCLEO-F446RE USART2 (ST-Link Virtual COM Port)
; Pins: PA2 (TX), PA3 (RX)

[stlink_vcp]
driver_name=dmuart
baudrate=921600
databits=8
parity=none
stopbits=1
flowcontrol=none
instance=2

[stlink_vcp_tx]
driver_name=dmgpio
pin=PA2
mode=alternate
alternate_function=7
speed=maximum
output_circuit=push_pull
pull=up

[stlink_vcp_rx]
driver_name=dmgpio
pin=PA3
mode=alternate
alternate_function=7
pull=up
