; STM32F769I-DISCOVERY USART6 (Arduino connector D0/D1)
; Pins: PC6 (TX), PC7 (RX)

[arduino_uart_tx]
driver_name=dmgpio
pin=PC6
mode=alternate
alternate_function=8
speed=maximum
output_circuit=push_pull
pull=up

[arduino_uart_rx]
driver_name=dmgpio
pin=PC7
mode=alternate
alternate_function=8
pull=up

[arduino_uart]
driver_name=dmuart
baudrate=921600
databits=8
parity=none
stopbits=1
flowcontrol=none
instance=6
rx_ring_size=256
