; STM32F4-DISCOVERY USART2
; Pins: PA2 (TX), PA3 (RX)

[usart2]
driver_name=dmuart
baudrate=921600
databits=8
parity=none
stopbits=1
flowcontrol=none
instance=2

[usart2_tx]
driver_name=dmgpio
pin=PA2
mode=alternate
alternate_function=7
speed=maximum
output_circuit=push_pull
pull=up

[usart2_rx]
driver_name=dmgpio
pin=PA3
mode=alternate
alternate_function=7
pull=up
