; STM32F4-DISCOVERY USART2
; Pins: PA2 (TX), PA3 (RX)

[usart2_tx]
driver_name=dmgpio
driver_order=1
pin=PA2
mode=alternate
alternate_function=7
speed=maximum
output_circuit=push_pull
pull=up

[usart2_rx]
driver_name=dmgpio
driver_order=1
pin=PA3
mode=alternate
alternate_function=7
pull=up

[usart2]
driver_name=dmuart
driver_order=1
baudrate=921600
databits=8
parity=none
stopbits=1
flowcontrol=none
instance=2
rx_ring_size=256
rx_ring_wait_mode=some_data
