; STM32F4-DISCOVERY USART1
; Pins: PB6 (TX), PB7 (RX)

[usart1_tx]
driver_name=dmgpio
driver_order=1
pin=PB6
mode=alternate
alternate_function=7
speed=maximum
output_circuit=push_pull
pull=up

[usart1_rx]
driver_name=dmgpio
driver_order=1
pin=PB7
mode=alternate
alternate_function=7
pull=up

[usart1]
driver_name=dmuart
driver_order=1
baudrate=921600
databits=8
parity=none
stopbits=1
flowcontrol=none
instance=1
rx_ring_size=256
rx_ring_wait_mode=some_data
