; NUCLEO-F767ZI USART3 (ST-Link Virtual COM Port)
; Pins: PD8 (TX), PD9 (RX)

[stlink_vcp_tx]
driver_name=dmgpio
driver_order=3
pin=PD8
mode=alternate
alternate_function=7
speed=maximum
output_circuit=push_pull
pull=up

[stlink_vcp_rx]
driver_name=dmgpio
driver_order=3
pin=PD9
mode=alternate
alternate_function=7
pull=up

[stlink_vcp]
driver_name=dmuart
driver_order=3
baudrate=921600
databits=8
parity=none
stopbits=1
flowcontrol=none
instance=3
rx_ring_size=256
rx_ring_wait_mode=some_data
