; NUCLEO-F411RE USART1 (Arduino connector D0/D1)
; Pins: PA9 (TX), PA10 (RX)

[arduino_uart_tx]
driver_name=dmgpio
driver_order=1
pin=PA9
mode=alternate
alternate_function=7
speed=maximum
output_circuit=push_pull
pull=up

[arduino_uart_rx]
driver_name=dmgpio
driver_order=1
pin=PA10
mode=alternate
alternate_function=7
pull=up

[arduino_uart]
driver_name=dmuart
driver_order=1
baudrate=921600
databits=8
parity=none
stopbits=1
flowcontrol=none
instance=1
rx_ring_size=256
